### ISSUE TITLE
Le fichier portail.cgi

### ISSUE THREAD

**Issue by Eolange** [Noethys/Connecthys#12]
Bonjour, pour ma ville, nous installons le portail cependant nous sommes chez ovh version mutualisé pro.  et je ne trouve pas de fichier portail.cgi. Ou est-il ? 

Si je vais sur l’accueil j'ai un message d'erreur : 
Le Portail Famille
Le portail est correctement installé mais n'a pas encore été synchronisé par l'administrateur.

Doc d'installation : 
Avec votre client FTP (Filezilla par exemple), appliquez la valeur 755 aux droits d'accès du fichier "portail.cgi" du répertoire connecthys
Chargez la page http://www.monsite.com/connecthys/portail.cgi/ pour ouvrir le portail

Merci pour votre aide.

**Comment by Noethys** [comment]
Bonsoir,

Il y a en effet une erreur dans la doc que j'avais fait au lancement : il s'agit désormais du fichier **connecthys.cgi** qui est à la racine du répertoire d'installation.

Ivan
