### ISSUE TITLE
Comment débuter le développement?

### ISSUE THREAD

**Issue by maximus49000** [Noethys/Connecthys#18]
Bonjour !

Je me lance dans le développement sur Connecthys pour rajouter des fonctionnalités spécifiques à mon association directement dans le logiciel. Après importation Git, et après avoir lancé le fichier run.py directement sur Windows, j'arrive bien à accéder au portail en local avec le "localhost:5000", mais j'ai le message suivant : "Le portail est correctement installé mais n'a pas encore été synchronisé par l'administrateur."

Ainsi, comment pouvoir accéder à la plateforme pour pouvoir tester les modifications? Merci d'avance pour votre réponse, et si cela m'est possible je proposerai bien sur mes modifications à la communauté !

Cordialement.

maximus49000

**Comment by Noethys** [comment]
Bonjour et bienvenue,

Il faut synchroniser Connecthys depuis Noethys. Pour cela, il faut aller dans Noethys > Menu Outils > Connecthys pour saisir les différents paramètres de connexion puis synchroniser (Bouton Outils > Synchroniser les données). Je conseille de cocher également "Activer sur cet ordinateur" dans la configuration.

Ivan

**Comment by Noethys** [comment]
Il y a peut-être un souci d'installation ? Il faudrait aller dans le **debug.log** qui se trouve dans le répertoire Connecthys pour repérer d'où vient l'erreur.

Il faut savoir que j'ai fait beaucoup de modifications cette semaine sur Connecthys mais que je n'ai pas encore publié. Ca sera fait dans les jours à venir. Je conseille donc de travailler plutôt sur la future version pour éviter trop de conflits sur Github.

Ivan

**Comment by maximus49000** [comment]
Très bien. Je vais donc m’entraîner avec cette version en attendant que la prochaine version sorte dans ce cas la ! ;)

Concernant le debug je vais aller voir de suite si il y a eu une erreur lors de l'exécution.

Enfin et j'arrête de t'importuner, des choses à savoir sur le code en lui même spécifique à cette application ou non?

Cordialement.

Maxime

**Comment by Noethys** [comment]
Je ne vois pas ce qui pourrait être précisé, excepté peut-être le fait qu'il n'y a que peu de code dans Connecthys : Noethys prépare beaucoup les données à envoyer à Connecthys lors de la synchronisation. C'est d'ailleurs là la complexité de Connecthys : il n'accède pas directement à la base de données de Noethys. Une grande partie du travail est donc effectué en amont et en aval (traitement des demandes) par Noethys. 

Ivan

**Comment by Noethys** [comment]
En théorie, il n'y a pas de subtilités particulières. Ce genre de code suffit : 

```
@app.route('/detail_envoi_reservations')
@login_required
def detail_envoi_reservations():
    if current_user.role != "famille" :
        return redirect(url_for('logout'))
    # Suite du code ici...
```

Ivan

**Comment by maximus49000** [comment]
C'est exactement ce que je fais dans la page views.py avec 👍 
@app.route('/inscriptioncommune', methods=['GET', 'POST'])
def inscriptioncommune():
    return redirect(url_for('login'))

ceci n'est qu'un test pour le moment, d'ou la redirection vers le login, mais lorsque j'écris : localhost:5000/inscriptioncommune, j'ai le fameux message : 

Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

de plus, lorsque j'essaye de récupérer son url avec url_for('inscriptioncommune'), dans un nouveau bouton créé dans la page login, j'ai un message d'erreur qui me dit que la page n'existe pas... il n'y a pas de manipulation particulière à faire normalement pour que les @app.route soient pris en compte !

(bien sur j'ai relancé le serveur après sauvegarde des modifications).

**Comment by Noethys** [comment]
Pour ma part, quand j'écris ça dans views.py : 

```
@app.route('/inscriptioncommune', methods=['GET', 'POST'])
def inscriptioncommune():
    return redirect(url_for('login'))
```

Ca fonctionne sans problème. Je ne sais pas où est l'erreur.

Il faudrait peut-être jeter un coup d'oeil sur la documentation de Flask.

Ivan

**Comment by maximus49000** [comment]
J'ai tout réinstaller au niveau des composants pyrhon, et apès de nombreuses heures d'incompréhension, mon code marche enfin. Bizarre ce bug, mais la réinstallation a tout réparé. Merci Ivan pour l'aide !

Bonne soirée.

Maxime

**Comment by Noethys** [comment]
Ok parfait. 

Je viens de publier la nouvelle version de Connecthys (0.6.5). Je conseille d'installer la nouvelle Beta de Noethys (Version 1.2.5.2 : Menu Téléchargements > Version Beta) et de faire une synchro. Noethys mettra alors à jour Connecthys automatiquement. C'est la méthode la plus simple.

Ivan

**Comment by maximus49000** [comment]
Petite question sur le règlement en ligne : pourquoi avoir pris Payzen qui demande un prix par mois alors que

**Comment by Noethys** [comment]
alors que... ?
