### ISSUE TITLE
synchronisation non fonctionelle avec mysql

### ISSUE THREAD

**Issue by mpasteur** [Noethys/Connecthys#2]
lorsque l'on configure connecthys avec mysq la synchronisation ne fonctionne pas a cause des tests d'intégrité réferentielle. Les tables doivent être vidées dans le bon ordre.
si personne ne traite le sujet je peux essayer de m'en charger...

**Comment by mpasteur** [comment]
fail... la table des reservations n'est pas vidée lors de l'import alors que la table des inscriptions l'est...
du coup ca plante. messieurs les développeurs j'ai besoin de vous....

**Comment by Noethys** [comment]
Je viens de commencer mes tests sur MySQL : Il y a en effet un sacré souci.
Le problème est que je n'arrive pas à le résoudre. Visiblement, ça vient
des foreignkey. J'ai essayé beaucoup de choses, mais ça coince toujours
autant. Si tu as une idée, je suis preneur !

2016-09-14 22:14 GMT+02:00 Marc Pasteur <notifications@github.com>:

**Comment by mpasteur** [comment]
Bonsoir Ivan.  J'ai justement réfléchi au problème et je ne vois pas
d'autre solution que d'enlever une des foreignkey à priori celle de la
table portail_action mais cela demande plus de tests...

**Comment by mpasteur** [comment]
la suppression des tables est fonctionnelle avec la séquence suivante:
`ALTER TABLE `connect`.`portail_reservations` 
DROP FOREIGN KEY `portail_reservations_ibfk_2`,
DROP FOREIGN KEY `portail_reservations_ibfk_1`;
ALTER TABLE `connect`.`portail_reservations` 
DROP INDEX `IDunite` ,
DROP INDEX `IDinscription` ;

DROP TABLE portail_cotisations_manquantes;
DROP TABLE portail_factures;
DROP TABLE portail_types_pieces;
DROP TABLE portail_users;
DROP TABLE portail_pieces_manquantes;
DROP TABLE portail_reglements;

DROP TABLE portail_consommations;
DROP TABLE portail_periodes;
DROP TABLE portail_ouvertures;
DROP TABLE portail_unites;
DROP TABLE portail_inscriptions;
DROP TABLE portail_groupes;
DROP TABLE portail_activites;
DROP TABLE portail_individus;
`

mais je n'ai pas encore assez creuser dans le code pour savoir si le fait de potentiellement supprimer l'intégrité référentielle  a une incidence ailleurs...

**Comment by mpasteur** [comment]
cf PR https://github.com/Noethys/Connecthys/pull/3

**Comment by Noethys** [comment]
Merci pour ta solution mais elle ne fonctionne pas pour moi. J'ai toujours un problème d'intégrité. Tes tables contenaient bien des données lors de tes tests ? J'y ai passé des heures depuis hier et je ne trouve toujours pas comment régler le problème...

**Comment by mpasteur** [comment]
Bonjour Ivan.  Oui je l'ai refait plusieurs fois après et pas de problème
pour moi.  J'ai bien des données de réservation car j'ai joué avec pour
voir le fonctionnement...  Peux-tu me mettre le message d'erreur exact ?

**Comment by Noethys** [comment]
A priori, j'ai trouvé une astuce qui fonctionne. Il m'a fallu le temps :(
