### ISSUE TITLE
Intégration d'eopayment

### ISSUE THREAD

**Issue by bdauvergne** [Noethys/Connecthys#29]
Bonjour,

Je vois que vous avez intégré eopayment dans votre logiciel, mais je ne vois trace ni de notre licence ni notre copyright (www.entrouvert.com), peut-être ai-je mal cherché, dans le cas contraire pourriez-vous ajouter ces informations (au README éventuellement).

Cordialement,

Benjamin Dauvergne

**Comment by Noethys** [comment]
Bonjour,

Je viens de regarder ça et en effet, je constate la même chose. Cette intégration avait été effectuée par un contributeur et je n'avais pas vérifié la présence de la licence dans le code. Désolé pour cette maladresse, ce sera corrigé dans les jours à venir.

Bonne journée,

Ivan

**Comment by Noethys** [comment]
Bonjour,

La licence a bien été intégrée à chaque fichier de la librairie.

Bonne journée,

Ivan
