### ISSUE TITLE
Reservation sur une date passée

### ISSUE THREAD

**Issue by mpasteur** [Noethys/Connecthys#4]
Conformément a ce que dis Fred.th (http://www.noethys.com/index.php/forum-34/connecthys-le-portail-internet/3585-connecthys-le-portail-internet?start=40#14378) il ne doit pas etre possible de saisir une réservation sur une date antérieure et ce quelque soit les contraintes définies sur l'activité.

**Comment by Noethys** [comment]
Modification ajoutée
