### ISSUE TITLE
Mysql : Freeze lors de la synchronisation sur l'instruction DROP TABLE portail_actions

### ISSUE THREAD

**Issue by mpasteur** [Noethys/Connecthys#9]
Avec mysql la synchronisation "freeze" indéfiniment.
Après analyse il apparaît que cela est du à une session sql non terminée puis un DROP TABLE sur la même table.
Correction en cours...

**Comment by mpasteur** [comment]
cf #10

**Comment by Noethys** [comment]
Modification intégrée. Merci !
